# Generated by Django 5.0 on 2025-03-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['publish']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['publish']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['publish']},
        ),
    ]
