# Generated by Django 5.0 on 2025-03-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_education_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['publish'], name='portfolio_e_publish_8e4e71_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['publish'], name='portfolio_e_publish_e304e4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['publish'], name='portfolio_p_publish_fa8ee1_idx'),
        ),
    ]
